### ISSUE TITLE
can't download clone.bundle

### ISSUE THREAD

**Issue by zhuangbiaowei** [esrlabs/git-repo#5]
fatal: Cannot get https://github.com/esrlabs/git-repo/clone.bundle

I try to download this file:"clone.bundle" via web browser. but github.com
give me 404 not found.

**Comment by mputz86** [comment]
Thank you very much - but you have to help me out: why are you trying to download this file? :)

**Comment by mputz86** [comment]
Hey there: just had the same issue: this message should definitely not crash your repo - in my case it was due to a broken VPN (ie network connection) that this error seemed to be the root cause (but was not, to fetch the clone.bundle should just be an attempt, not a show stopper). Fixing the internet connection fetched the repo repository soomthly. Just tell me if you run on another path into this error message and it still occurs.
Thank you very much!
