### ISSUE TITLE
fatal: manifest 'default.xml' not available??

### ISSUE THREAD

**Issue by MenuuTUX** [esrlabs/git-repo#84]
Okay so I was trying to clone a android recovery and I got a fatal error :

############################################################################################

aqua@aqua-HP-EliteBook-8460p:~/RedWolf$ repo init -u git://github.com/RedWolfRecovery/rw_manifest.git -b rw
Downloading Repo source from https://gerrit.googlesource.com/git-repo
Downloading manifest from git://github.com/RedWolfRecovery/rw_manifest.git
remote: Enumerating objects: 1294, done.
remote: Total 1294 (delta 0), reused 0 (delta 0), pack-reused 1294
fatal: manifest 'default.xml' not available
fatal: <project> invalid "path": TeamWin/.repo/frameworks/base: bad component: .repo

#############################################################################################

How do I solve this?

**Comment by grv87** [comment]
@friendlymaninthisworld, the error is in the manifest you are trying to use.

IIRC, you can't have `.repo` in path since this directory is used by git-repo internally. Manifest author should choose another path, without `.repo`.


Also, looks like you use original Google git-repo version. It has [its own bug tracker](https://bugs.chromium.org/p/gerrit/issues/list?q=component:repo), you should report your issues there.

**Comment by MenuuTUX** [comment]
Thank you it worked!!!

**Comment by MenuuTUX** [comment]
For an explination, I :
"git clone https://android.googlesource.com/tools/repo"
the I used 
"repo init" in the folder
